name: MovieCLIP
channels:
  - defaults
dependencies:
  - python=3.7
  - ffmpeg
  - pip
  - pip:
    - "torch==1.9.0+cu111"
    - "torchvision==0.10.0+cu111"
    - "torchaudio==0.9.0"
    - "-f https://download.pytorch.org/whl/torch_stable.html"
    - info-nce-pytorch
    - numpy==1.21.6
    - matplotlib==3.5.3
    - pyyaml==6.0.1
    - tensorboardx==2.6.2.2
    - ftfy
    - regex
    - tqdm
    - git+https://github.com/openai/CLIP.git
    - moviepy==1.0.3
    - librosa==0.10.1