training_dataset:
  type: CustomDataset
  args:
    folder: '/home/miislab-server/Alan/Alan_shared/MovieNet/feature'

val_dataset:
  type: CustomDataset
  args:
    folder: '/home/miislab-server/Alan/Alan_shared/MovieNet/val_feature'

data_loader:
  type: DataLoader
  args:
    batch_size: 64
    shuffle: true

model:
  type: CLMP
  args:
    embedding_dim: 512
    num_heads: 4
    ff_hidden_dim: 1024
    num_block: 2
    dropout: 0.1
    max_len: 600

optimizer:
  type: Adam
  args:
    lr: 0.0001

lr_scheduler:
  type: CosineAnnealingLR
  args:
    T_max: 4000

loss:
  type: DescriptionWithGenresContrastiveLoss
  args:
    temperature: 0.1  
    v_d_weight: 1
    a_d_weight: 1 
    va_d_weight: 1 
    v_g_weight: 1 
    a_g_weight: 1 
    va_g_weight: 1

trainer:
  args:
    use_check_point: false
    check_point: ''
    epochs: 100000

